//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNELINFO
    {
        public decimal ID { get; set; }
        public string ChannelStyle { get; set; }
        public string ChannelCode { get; set; }
        public string CnName { get; set; }
        public string EnName { get; set; }
        public string Status { get; set; }
    }
}
